spring:
  application:
    name: demo

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
  servlet:
    jsp:
      prefix: /WEB-INF/jsp/error-page
      suffix: .jsp

custom:
  message: "Profilo DEV"


  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/database_corso
    username: postgres
    password: Tyson1209
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Endpoints utili:
# - http://localhost:8080/docenti/lista
# - http://localhost:8080/discenti/lista
# - http://localhost:8080/corso/lista